In [1]:
print("Start")

Start


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
#2D Array
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
#Use of ndim property of numpy array
print(a.ndim)
print(b.ndim)

1
2


In [9]:
#To check datatype of numpy array=dtype
print(a.dtype)
print(b.dtype)

int64
int64


In [10]:
#To use the item size
print(a.itemsize)
print(b.itemsize)

8
8


In [11]:
#Shape tells no of rows and columns and size will count number of element
print(a.size)
print(b.size)
print(a.shape)
print(b.shape)

3
6
(3,)
(2, 3)


In [13]:
#Reshape is used to change dimensions
print(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [18]:
#Linspace=returns evenly spaced numbers over a specified interval
c=np.linspace(1,3,50)
print(c)

[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ]


In [20]:
#Use of min ,sum and max function
print("Maximum value=",a.max())
print("Minimum value=",a.min())
print("Sum of values=",a.sum())

Maximum value= 3
Minimum value= 1
Sum of values= 6
